---
ubuntu_password: thhKoFbaif2
python_version: 3.6.1
chainer_version: v2.0.0
cudnn_version: v6-cuda8
cuda_url: https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
